<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ModelosOntologas</name>
   <tag></tag>
   <elementGuidId>5ba093a5-b5da-43f6-99c0-12f46b11508f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modelos/Ontologías</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;wf-poppins-n4-active wf-poppins-n7-active wf-poppins-n6-active wf-opensans-n6-active wf-poppins-n5-active wf-opensans-n4-active wf-opensans-n5-active wf-poppins-n3-active wf-opensans-n7-active wf-opensans-n3-active wf-active&quot;]/body[@class=&quot;page-header-fixed  page-content-white page-sidebar-closed&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;page-sidebar-wrapper&quot;]/div[@class=&quot;page-sidebar navbar-collapse collapse&quot;]/ul[@class=&quot;page-sidebar-menu page-header-fixed page-sidebar-menu-closed&quot;]/li[@class=&quot;nav-item&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link nav-toggle&quot;]/span[@class=&quot;title&quot;]</value>
   </webElementProperties>
</WebElementEntity>
