<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_General</name>
   <tag></tag>
   <elementGuidId>910515d9-5723-453f-b0cd-576e7d5fc5a1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_3&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 col-md-4 col-xs-12&quot;]/div[@class=&quot;mt-element-list&quot;]/div[@class=&quot;mt-list-container list-default ext-1 group&quot;]/div[@class=&quot;datamodel-types&quot;]/a[@class=&quot;list-toggle-container collapsed&quot;]/div[@class=&quot;list-toggle bg-grey-mint uppercase&quot;]/span[2]</value>
   </webElementProperties>
</WebElementEntity>
