FROM centos/mysql-57-centos7

# Metadata
LABEL module.maintainer="plataformasofia2@indra.es" \
	  module.name="schedulerdb"	

# MySQL environment
ENV MYSQL_ROOT_PASSWORD="changeIt!" \
    MYSQL_USER="indra" \
    MYSQL_PASSWORD="select4cities2018" \
    MYSQL_DATABASE="sofia2_s4c_scheduler" \
    MYSQL_MAX_ALLOWED_PACKET="536870912" \
    MYSQL_LOWER_CASE_TABLE_NAMES="1"  

# Copy to images mysql path
COPY quartz-schema.sql /docker-entrypoint-initdb.d/quartz-schema.sql

USER mysql

EXPOSE 3306